### ISSUE TITLE
why don't you using cling

### ISSUE THREAD

**Issue by zhaohansprt** [treefrogframework/cpi#1]
although it is big  but it is extremly extensive

**Comment by treefrogframework** [comment]
Cpi is tiny and efficient, but needs a compiler to run.
Cling has executive-mode?

**Comment by zhaohansprt** [comment]
yes it has  ,try it  https://root.cern.ch/download/cling/   under unbuntu   
I dont known  how it can run in windows,  but some one does  -> google  qtcling

**Comment by treefrogframework** [comment]
Thanks.

I enjoy coding.

**Comment by zhaohansprt** [comment]
not  only  executive-mode  but also you  can  executively  include libraries  and with jit

**Comment by stefanos82** [comment]
@treefrogframework your project looks promising, well done.

I'm interested about performance though. Are there any plans to add something like benchmarks comparing it to Cling?

As far as I know, Cling is rather slow interpreter. 

How bout cpi? How fast does it perform for huge calculations from inside interpreter?

Keep up the good work.

**Comment by treefrogframework** [comment]
Cpi is just calling a compiler, g++ or clang++, so may not be strictly interpreter.
Recent compiler is fast, clang++ specially.

**Comment by zhaohansprt** [comment]
I may just want to introduce you  some  really cool and powerful (in my submission) staff
