### ISSUE TITLE
CPI doesn't recognize pkgconfig compile options

### ISSUE THREAD

**Issue by RobolabUACJ** [treefrogframework/cpi#11]
I've been using CPI throughout the year, and while it has been working fine, there's one issue I stumbled upon when making several tests with a wide variety of libraries.

When trying to use pkgconfig compilation flags, CPI seems to not recognize them properly.
For example, trying to use this compilation options:

```
//CompileOptions: -lm -larmadillo -pthread -lboost_iostreams -lboost_system -lboost_filesystem `pkg-config --cflags --libs playerc++ opencv4` -I/usr/local/include/player-3.1 -I/usr/include/tirpc -I/usr/include/opencv4 
```

Gives the following errors on runtime:
```
>>> Compilation error
g++: error: unrecognized command-line option ‘--cflags’
g++: error: unrecognized command-line option ‘--libs’; did you mean ‘--libs=’?
```

Separating the libraries for both Player and OpenCV4 does make the code run properly though:
```
//CompileOptions: -lm -larmadillo -pthread -lboost_iostreams -lboost_system -lboost_filesystem -lplayerc -lplayerc++ -lopencv_video -lopencv_core -lopencv_imgcodecs -lopencv_highgui -lopencv_features2d -I/usr/local/include/player-3.1 -I/usr/include/tirpc -I/usr/include/opencv4 
```
It seems that CPI isn't properly recognizing what's inside the apostrophes as a single pkg-config command.

Implementing pkgconfig compilation flags could help a lot to reduce the amount of manual typing it would require to find each and every library related to a specific package, in this case, OpenCV4, since I did find an issue of a specific portion of code giving me undefined references because I missed a specific library from OpenCV (imcodecs in my case), while with pkgconfig all sub-libraries would be included by default.

**Comment by treefrogframework** [comment]
@RobolabUACJ 
Thank you for information.
Could you try it out because I fixed the issue.
18dd6e25072fb6b9986932d4b485b2d48962ea6a

**Comment by RobolabUACJ** [comment]
@treefrogframework thank you.
I just pulled the latest changes to the compiler.cpp file, and after compiling it, the code now runs properly with the pkgconfig command.
Thanks for the update! I'm closing this issue now.
