### ISSUE TITLE
Is there any way I can make it support c++14 or later ? I like it a lot, I am using Ubuntu

### ISSUE THREAD

**Issue by cata0309** [treefrogframework/cpi#2]

**Comment by treefrogframework** [comment]
You can set to the CXXFLAGS parameter in /home/(your account)/.config/cpi/cpi.conf file.

CXXFLAGS=-fPIC -pipe -std=gnu++14 -D_REENTRANT

**Comment by cata0309** [comment]
Thank you

vin., 26 apr. 2019, 08:28 TreeFrog Framework <notifications@github.com> a
scris:

**Comment by cata0309** [comment]
Can I go higher with the configuration ? Like c++ 17 in the future ?

vin., 26 apr. 2019, 08:29 Catalin Marincia <catalinmarincia@gmail.com> a
scris:

**Comment by cata0309** [comment]
there is not such a folder in the .config folder in my home directory, I checked the show hidden files box, but nothing. Can you help me please?

**Comment by cata0309** [comment]
I made one and created a cpi.config file and entered the text you said. Thank you

**Comment by cata0309** [comment]
Is there any detailed docummentation for this tool ?

**Comment by treefrogframework** [comment]
Fix in ea56d92baa92d5a931e.

> Is there any detailed docummentation for this tool ?

No. Show helps of the command. Type ".help".
