### ISSUE TITLE
Compilation error encountered

### ISSUE THREAD

**Issue by Endericedragon** [treefrogframework/cpi#5]
I've successfully built cpi from its source code with the help of MSVC 2017 and QT 5.13.2,  without receiving any error or warning. However, when I tried to run the codes below, I got a "Compilation error":
```
#include <iostream>

int main() {
    std::cout << "Hello cpi!\n";
    return 0;
}
```
What made me more confused is that I tried to run some codes in interactive mode, and I got no return:
```
Cpi 2.0.0
Type ".help" for more information.
Loaded INI file: C:/Users/endericedragon/AppData/Roaming/cpi/cpi.ini
cpi> 3 << 2;

cpi>
```
I wonder if there is any solution to this? Thanks.

**Comment by treefrogframework** [comment]
Version 2.0.2 release.
Try it please.
https://github.com/treefrogframework/cpi/releases
