### ISSUE TITLE
Can cpi be built with Qt4?

### ISSUE THREAD

**Issue by barracuda156** [treefrogframework/cpi#9]
Asking this, since Qt5 and later are broken for PPC. Qt4 builds though.

**Comment by treefrogframework** [comment]
I have never tried it.
You can try it!

See [Actions](https://github.com/treefrogframework/cpi/actions).

**Comment by barracuda156** [comment]
> I have never tried it.
> 
> You can try it!
> 
> See [Actions](https://github.com/treefrogframework/cpi/actions).

Thank you! I will check that.
